import Layout from "@/components/Layout";
import Rtppro from "@/components/Rtp-pro";
import Image from "next/image";

const Pragmatic = () => {
  const Menus = [
    { img: "/pragmatic/1.webp", alt: "pragmatic1" },
    { img: "/pragmatic/2.webp", alt: "pragmatic2" },
    { img: "/pragmatic/3.webp", alt: "pragmatic3" },
    { img: "/pragmatic/4.webp", alt: "pragmatic4" },
    { img: "/pragmatic/5.webp", alt: "pragmatic5" },
    { img: "/pragmatic/6.webp", alt: "pragmatic6" },
    { img: "/pragmatic/7.webp", alt: "pragmatic7" },
    { img: "/pragmatic/8.webp", alt: "pragmatic8" },
    { img: "/pragmatic/9.webp", alt: "pragmatic9" },
    { img: "/pragmatic/10.webp", alt: "pragmatic10" },
    { img: "/pragmatic/11.webp", alt: "pragmatic11" },
    { img: "/pragmatic/12.webp", alt: "pragmatic12" },
    { img: "/pragmatic/13.webp", alt: "pragmatic13" },
    { img: "/pragmatic/14.webp", alt: "pragmatic14" },
    { img: "/pragmatic/15.webp", alt: "pragmatic15" },
    { img: "/pragmatic/16.webp", alt: "pragmatic16" },
    { img: "/pragmatic/17.webp", alt: "pragmatic17" },
    { img: "/pragmatic/18.webp", alt: "pragmatic18" },
    { img: "/pragmatic/19.webp", alt: "pragmatic19" },
    { img: "/pragmatic/20.webp", alt: "pragmatic20" },
    { img: "/pragmatic/21.webp", alt: "pragmatic21" },
    { img: "/pragmatic/22.webp", alt: "pragmatic22" },
    { img: "/pragmatic/23.webp", alt: "pragmatic23" },
    { img: "/pragmatic/24.webp", alt: "pragmatic24" },
    { img: "/pragmatic/25.webp", alt: "pragmatic25" },
    { img: "/pragmatic/26.webp", alt: "pragmatic26" },
    { img: "/pragmatic/27.webp", alt: "pragmatic27" },
    { img: "/pragmatic/28.webp", alt: "pragmatic28" },
    { img: "/pragmatic/29.webp", alt: "pragmatic29" },
    { img: "/pragmatic/30.webp", alt: "pragmatic30" },
    { img: "/pragmatic/31.webp", alt: "pragmatic31" },
    { img: "/pragmatic/32.webp", alt: "pragmatic32" },
    { img: "/pragmatic/33.webp", alt: "pragmatic33" },
    { img: "/pragmatic/34.webp", alt: "pragmatic34" },
    { img: "/pragmatic/35.webp", alt: "pragmatic35" },
    { img: "/pragmatic/36.webp", alt: "pragmatic36" },
    { img: "/pragmatic/37.webp", alt: "pragmatic37" },
    { img: "/pragmatic/38.webp", alt: "pragmatic38" },
    { img: "/pragmatic/39.webp", alt: "pragmatic39" },
    { img: "/pragmatic/40.webp", alt: "pragmatic40" },
    { img: "/pragmatic/41.webp", alt: "pragmatic41" },
    { img: "/pragmatic/42.webp", alt: "pragmatic42" },
    { img: "/pragmatic/43.webp", alt: "pragmatic43" },
    { img: "/pragmatic/44.webp", alt: "pragmatic44" },
    { img: "/pragmatic/45.webp", alt: "pragmatic45" },
    { img: "/pragmatic/46.webp", alt: "pragmatic46" },
    { img: "/pragmatic/47.webp", alt: "pragmatic47" },
    { img: "/pragmatic/48.webp", alt: "pragmatic48" },
    { img: "/pragmatic/49.webp", alt: "pragmatic49" },
    { img: "/pragmatic/50.webp", alt: "pragmatic50" },
    { img: "/pragmatic/51.webp", alt: "pragmatic51" },
    { img: "/pragmatic/52.webp", alt: "pragmatic52" },
    { img: "/pragmatic/53.webp", alt: "pragmatic53" },
    { img: "/pragmatic/54.webp", alt: "pragmatic54" },
    { img: "/pragmatic/55.webp", alt: "pragmatic55" },
    { img: "/pragmatic/56.webp", alt: "pragmatic56" },
    { img: "/pragmatic/57.webp", alt: "pragmatic57" },
    { img: "/pragmatic/58.webp", alt: "pragmatic58" },
    { img: "/pragmatic/59.webp", alt: "pragmatic59" },
    { img: "/pragmatic/60.webp", alt: "pragmatic60" },
    { img: "/pragmatic/61.webp", alt: "pragmatic61" },
    { img: "/pragmatic/62.webp", alt: "pragmatic62" },
    { img: "/pragmatic/63.webp", alt: "pragmatic63" },
    { img: "/pragmatic/64.webp", alt: "pragmatic64" },
    { img: "/pragmatic/65.webp", alt: "pragmatic65" },
    { img: "/pragmatic/66.webp", alt: "pragmatic66" },
    { img: "/pragmatic/67.webp", alt: "pragmatic67" },
    { img: "/pragmatic/68.webp", alt: "pragmatic68" },
    { img: "/pragmatic/69.webp", alt: "pragmatic69" },
    { img: "/pragmatic/70.webp", alt: "pragmatic70" },
    { img: "/pragmatic/71.webp", alt: "pragmatic71" },
    { img: "/pragmatic/72.webp", alt: "pragmatic72" },
    { img: "/pragmatic/73.webp", alt: "pragmatic73" },
    { img: "/pragmatic/74.webp", alt: "pragmatic74" },
    { img: "/pragmatic/75.webp", alt: "pragmatic75" },
    { img: "/pragmatic/76.webp", alt: "pragmatic76" },
    { img: "/pragmatic/77.webp", alt: "pragmatic77" },
    { img: "/pragmatic/78.webp", alt: "pragmatic78" },
    { img: "/pragmatic/79.webp", alt: "pragmatic79" },
    { img: "/pragmatic/80.webp", alt: "pragmatic80" },
    { img: "/pragmatic/81.webp", alt: "pragmatic81" },
    { img: "/pragmatic/82.webp", alt: "pragmatic82" },
    { img: "/pragmatic/83.webp", alt: "pragmatic83" },
    { img: "/pragmatic/84.webp", alt: "pragmatic84" },
    { img: "/pragmatic/85.webp", alt: "pragmatic85" },
    { img: "/pragmatic/86.webp", alt: "pragmatic86" },
    { img: "/pragmatic/87.webp", alt: "pragmatic87" },
    { img: "/pragmatic/88.webp", alt: "pragmatic88" },
    { img: "/pragmatic/89.webp", alt: "pragmatic89" },
    { img: "/pragmatic/90.webp", alt: "pragmatic90" },
    { img: "/pragmatic/91.webp", alt: "pragmatic91" },
    { img: "/pragmatic/92.webp", alt: "pragmatic92" },
    { img: "/pragmatic/93.webp", alt: "pragmatic93" },
    { img: "/pragmatic/94.webp", alt: "pragmatic94" },
    { img: "/pragmatic/95.webp", alt: "pragmatic95" },
    { img: "/pragmatic/96.webp", alt: "pragmatic96" },
    { img: "/pragmatic/97.webp", alt: "pragmatic97" },
    { img: "/pragmatic/98.webp", alt: "pragmatic98" },
    { img: "/pragmatic/99.webp", alt: "pragmatic99" },
    { img: "/pragmatic/100.webp", alt: "pragmatic100" },
    { img: "/pragmatic/101.webp", alt: "pragmatic101" },
    { img: "/pragmatic/102.webp", alt: "pragmatic102" },
    { img: "/pragmatic/103.webp", alt: "pragmatic103" },
    { img: "/pragmatic/104.webp", alt: "pragmatic104" },
    { img: "/pragmatic/105.webp", alt: "pragmatic105" },
    { img: "/pragmatic/106.webp", alt: "pragmatic106" },
    { img: "/pragmatic/107.webp", alt: "pragmatic107" },
    { img: "/pragmatic/108.webp", alt: "pragmatic108" },
    { img: "/pragmatic/109.webp", alt: "pragmatic109" },
    { img: "/pragmatic/110.webp", alt: "pragmatic110" },
    { img: "/pragmatic/111.webp", alt: "pragmatic111" },
    { img: "/pragmatic/112.webp", alt: "pragmatic112" },
    { img: "/pragmatic/113.webp", alt: "pragmatic113" },
    { img: "/pragmatic/114.webp", alt: "pragmatic114" },
    { img: "/pragmatic/115.webp", alt: "pragmatic115" },
    { img: "/pragmatic/116.webp", alt: "pragmatic116" },
    { img: "/pragmatic/117.webp", alt: "pragmatic117" },
    { img: "/pragmatic/118.webp", alt: "pragmatic118" },
    { img: "/pragmatic/119.webp", alt: "pragmatic119" },
    { img: "/pragmatic/120.webp", alt: "pragmatic120" },
    { img: "/pragmatic/121.webp", alt: "pragmatic121" },
    { img: "/pragmatic/122.webp", alt: "pragmatic122" },
    { img: "/pragmatic/123.webp", alt: "pragmatic123" },
    { img: "/pragmatic/124.webp", alt: "pragmatic124" },
    { img: "/pragmatic/125.webp", alt: "pragmatic125" },
    { img: "/pragmatic/126.webp", alt: "pragmatic126" },
    { img: "/pragmatic/127.webp", alt: "pragmatic127" },
    { img: "/pragmatic/128.webp", alt: "pragmatic128" },
    { img: "/pragmatic/129.webp", alt: "pragmatic129" },
    { img: "/pragmatic/130.webp", alt: "pragmatic130" },
    { img: "/pragmatic/131.webp", alt: "pragmatic131" },
    { img: "/pragmatic/132.webp", alt: "pragmatic132" },
    { img: "/pragmatic/133.webp", alt: "pragmatic133" },
    { img: "/pragmatic/134.webp", alt: "pragmatic134" },
    { img: "/pragmatic/135.webp", alt: "pragmatic135" },
    { img: "/pragmatic/136.webp", alt: "pragmatic136" },
    { img: "/pragmatic/137.webp", alt: "pragmatic137" },
    { img: "/pragmatic/138.webp", alt: "pragmatic138" },
    { img: "/pragmatic/139.webp", alt: "pragmatic139" },
    { img: "/pragmatic/140.webp", alt: "pragmatic140" },
    { img: "/pragmatic/141.webp", alt: "pragmatic141" },
    { img: "/pragmatic/142.webp", alt: "pragmatic142" },
    { img: "/pragmatic/143.webp", alt: "pragmatic143" },
    { img: "/pragmatic/144.webp", alt: "pragmatic144" },
    { img: "/pragmatic/145.webp", alt: "pragmatic145" },
    { img: "/pragmatic/146.webp", alt: "pragmatic146" },
    { img: "/pragmatic/147.webp", alt: "pragmatic147" },
    { img: "/pragmatic/148.webp", alt: "pragmatic148" },
    { img: "/pragmatic/149.webp", alt: "pragmatic149" },
    { img: "/pragmatic/150.webp", alt: "pragmatic150" },
    { img: "/pragmatic/151.webp", alt: "pragmatic151" },
    { img: "/pragmatic/152.webp", alt: "pragmatic152" },
    { img: "/pragmatic/153.webp", alt: "pragmatic153" },
    { img: "/pragmatic/154.webp", alt: "pragmatic154" },
    { img: "/pragmatic/155.webp", alt: "pragmatic155" },
    { img: "/pragmatic/156.webp", alt: "pragmatic156" },
    { img: "/pragmatic/157.webp", alt: "pragmatic157" },
    { img: "/pragmatic/158.webp", alt: "pragmatic158" },
    { img: "/pragmatic/159.webp", alt: "pragmatic159" },
    { img: "/pragmatic/160.webp", alt: "pragmatic160" },
    { img: "/pragmatic/161.webp", alt: "pragmatic161" },
    { img: "/pragmatic/162.webp", alt: "pragmatic162" },
    { img: "/pragmatic/163.webp", alt: "pragmatic163" },
    { img: "/pragmatic/164.webp", alt: "pragmatic164" },
    { img: "/pragmatic/165.webp", alt: "pragmatic165" },
    { img: "/pragmatic/166.webp", alt: "pragmatic166" },
    { img: "/pragmatic/167.webp", alt: "pragmatic167" },
    { img: "/pragmatic/168.webp", alt: "pragmatic168" },
    { img: "/pragmatic/169.webp", alt: "pragmatic169" },
    { img: "/pragmatic/170.webp", alt: "pragmatic170" },
    { img: "/pragmatic/171.webp", alt: "pragmatic171" },
    { img: "/pragmatic/172.webp", alt: "pragmatic172" },
    { img: "/pragmatic/173.webp", alt: "pragmatic173" },
    { img: "/pragmatic/174.webp", alt: "pragmatic174" },
    { img: "/pragmatic/175.webp", alt: "pragmatic175" },
    { img: "/pragmatic/176.webp", alt: "pragmatic176" },
    { img: "/pragmatic/177.webp", alt: "pragmatic177" },
    { img: "/pragmatic/178.webp", alt: "pragmatic178" },
    { img: "/pragmatic/179.webp", alt: "pragmatic179" },
    { img: "/pragmatic/180.webp", alt: "pragmatic180" },
    { img: "/pragmatic/181.webp", alt: "pragmatic181" },
    { img: "/pragmatic/182.webp", alt: "pragmatic182" },
    { img: "/pragmatic/183.webp", alt: "pragmatic183" },
    { img: "/pragmatic/184.webp", alt: "pragmatic184" },
    { img: "/pragmatic/185.webp", alt: "pragmatic185" },
    { img: "/pragmatic/186.webp", alt: "pragmatic186" },
    { img: "/pragmatic/187.webp", alt: "pragmatic187" },
    { img: "/pragmatic/188.webp", alt: "pragmatic188" },
    { img: "/pragmatic/189.webp", alt: "pragmatic189" },
    { img: "/pragmatic/190.webp", alt: "pragmatic190" },
    { img: "/pragmatic/191.webp", alt: "pragmatic191" },
    { img: "/pragmatic/192.webp", alt: "pragmatic192" },
    { img: "/pragmatic/193.webp", alt: "pragmatic193" },
    { img: "/pragmatic/194.webp", alt: "pragmatic194" },
    { img: "/pragmatic/195.webp", alt: "pragmatic195" },
    { img: "/pragmatic/196.webp", alt: "pragmatic196" },
    { img: "/pragmatic/197.webp", alt: "pragmatic197" },
    { img: "/pragmatic/198.webp", alt: "pragmatic198" },
    { img: "/pragmatic/199.webp", alt: "pragmatic199" },
    { img: "/pragmatic/200.webp", alt: "pragmatic200" },
    { img: "/pragmatic/201.webp", alt: "pragmatic201" },
    { img: "/pragmatic/202.webp", alt: "pragmatic202" },
    { img: "/pragmatic/203.webp", alt: "pragmatic203" },
    { img: "/pragmatic/204.webp", alt: "pragmatic204" },
    { img: "/pragmatic/205.webp", alt: "pragmatic205" },
    { img: "/pragmatic/206.webp", alt: "pragmatic206" },
    { img: "/pragmatic/207.webp", alt: "pragmatic207" },
    { img: "/pragmatic/208.webp", alt: "pragmatic208" },
    { img: "/pragmatic/209.webp", alt: "pragmatic209" },
    { img: "/pragmatic/210.webp", alt: "pragmatic210" },
    { img: "/pragmatic/211.webp", alt: "pragmatic211" },
    { img: "/pragmatic/212.webp", alt: "pragmatic212" },
    { img: "/pragmatic/213.webp", alt: "pragmatic213" },
    { img: "/pragmatic/214.webp", alt: "pragmatic214" },
    { img: "/pragmatic/215.webp", alt: "pragmatic215" },
    { img: "/pragmatic/216.webp", alt: "pragmatic216" },
    { img: "/pragmatic/217.webp", alt: "pragmatic217" },
    { img: "/pragmatic/218.webp", alt: "pragmatic218" },
    { img: "/pragmatic/219.webp", alt: "pragmatic219" },
    { img: "/pragmatic/220.webp", alt: "pragmatic220" },
    { img: "/pragmatic/221.webp", alt: "pragmatic221" },
    { img: "/pragmatic/222.webp", alt: "pragmatic222" },
    { img: "/pragmatic/223.webp", alt: "pragmatic223" },
    { img: "/pragmatic/224.webp", alt: "pragmatic224" },
    { img: "/pragmatic/225.webp", alt: "pragmatic225" },
    { img: "/pragmatic/226.webp", alt: "pragmatic226" },
    { img: "/pragmatic/227.webp", alt: "pragmatic227" },
    { img: "/pragmatic/228.webp", alt: "pragmatic228" },
    { img: "/pragmatic/229.webp", alt: "pragmatic229" },
    { img: "/pragmatic/230.webp", alt: "pragmatic230" },
    { img: "/pragmatic/231.webp", alt: "pragmatic231" },
    { img: "/pragmatic/232.webp", alt: "pragmatic232" },
    { img: "/pragmatic/233.webp", alt: "pragmatic233" },
    { img: "/pragmatic/234.webp", alt: "pragmatic234" },
    { img: "/pragmatic/235.webp", alt: "pragmatic235" },
    { img: "/pragmatic/236.webp", alt: "pragmatic236" },
    { img: "/pragmatic/237.webp", alt: "pragmatic237" },
    { img: "/pragmatic/238.webp", alt: "pragmatic238" },
    { img: "/pragmatic/239.webp", alt: "pragmatic239" },
    { img: "/pragmatic/240.webp", alt: "pragmatic240" },
    { img: "/pragmatic/241.webp", alt: "pragmatic241" },
    { img: "/pragmatic/242.webp", alt: "pragmatic242" },
    { img: "/pragmatic/243.webp", alt: "pragmatic243" },
    { img: "/pragmatic/244.webp", alt: "pragmatic244" },
    { img: "/pragmatic/245.webp", alt: "pragmatic245" },
    { img: "/pragmatic/246.webp", alt: "pragmatic246" },
    { img: "/pragmatic/247.webp", alt: "pragmatic247" },
    { img: "/pragmatic/248.webp", alt: "pragmatic248" },
    { img: "/pragmatic/249.webp", alt: "pragmatic249" },
    { img: "/pragmatic/250.webp", alt: "pragmatic250" },
    { img: "/pragmatic/251.webp", alt: "pragmatic251" },
    { img: "/pragmatic/252.webp", alt: "pragmatic252" },
    { img: "/pragmatic/253.webp", alt: "pragmatic253" },
    { img: "/pragmatic/254.webp", alt: "pragmatic254" },
    { img: "/pragmatic/255.webp", alt: "pragmatic255" },
    { img: "/pragmatic/256.webp", alt: "pragmatic256" },
    { img: "/pragmatic/257.webp", alt: "pragmatic257" },
    { img: "/pragmatic/258.webp", alt: "pragmatic258" },
    { img: "/pragmatic/259.webp", alt: "pragmatic259" },
    { img: "/pragmatic/260.webp", alt: "pragmatic260" },
    { img: "/pragmatic/261.webp", alt: "pragmatic261" },
    { img: "/pragmatic/262.webp", alt: "pragmatic262" },
    { img: "/pragmatic/263.webp", alt: "pragmatic263" },
    { img: "/pragmatic/264.webp", alt: "pragmatic264" },
    { img: "/pragmatic/265.webp", alt: "pragmatic265" },
    { img: "/pragmatic/266.webp", alt: "pragmatic266" },
    { img: "/pragmatic/267.webp", alt: "pragmatic267" },
    { img: "/pragmatic/268.webp", alt: "pragmatic268" },
    { img: "/pragmatic/269.webp", alt: "pragmatic269" },
    { img: "/pragmatic/270.webp", alt: "pragmatic270" },
  ];
  return (
    <>
      <Layout pageTitle="RTP KINGDOM">
        <ul className="grid grid-cols-4 gap-2">
          {Menus.map((menu, index) => (
            <li key={index} className="grid">
              <div className="flex items-center">
                <Image
                  className="w-full h-auto"
                  src={menu.img}
                  alt={menu.alt}
                  width={250}
                  height={115}
                />
              </div>
              <Rtppro />
            </li>
          ))}
        </ul>
      </Layout>
    </>
  );
};

export default Pragmatic;
